name = "Upgrader"
uuid = "393d3b9c-a553-4ba1-bbff-ea3bf71e75e8"
authors = ["vdayanand <venkatesh@juliacomputing.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[extras]
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"

[targets]
test = ["ReTest"]
